#!/sbin/openrc-run
# Copyright 2026 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

description="Q Pilot client service (Uni Hamburg follow-me printing)"
command="/usr/libexec/qpilot-client/qpilot-client-service"
command_background="yes"
command_user="qpilot:qpilot"
# The Q Pilot server sets the LPD port the service listens on to 515.
capabilities="^cap_net_bind_service"
no_new_privs="yes"
pidfile="/run/${RC_SVCNAME}.pid"
retry="TERM/10/KILL/5"

depend() {
	need net
	use dns
	before cupsd
}
